train:
  n_steps: 500000
  batch_size: 64
  log_interval: 50
  save_interval: 1000
  accumulation_steps: 1
optimizer:
  name: 'adamw'
  lr: 0.0003
  weight_decay: 0.03
  betas: [0.99, 0.99]
lr_scheduler:
  name: 'customized'
  warmup_steps: 5000
nnet:
  img_size: 16
  codebook_size: 1025
  embed_dim: 512
  depth: 6
  num_heads: 8
  mlp_ratio: 4
  qkv_bias: False
  num_classes: 1001
  use_checkpoint: False
  use_context: False
  skip: True
  classifier: True
muse:
  ignore_ind: -1
  smoothing: 0.1
dataset:
  name: 'imagenet256_features'
  path: '/pub3/qasim/probnat/imagenet256_vq_features'
  cfg: True
  p_uncond: 0.15
exp_name: probnat
sampling_type: small_transformer
resume_path: 'assets/nnet_ema.pth'
